name: Build and Push Docker Images to JFrog Artifactory

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU 🏗️
        uses: docker/setup-qemu-action@v1

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to JFrog 🐸  
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ARTIFACTORY_URL }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build and push 🐳
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ARTIFACTORY_URL }}/image1:latest
          labels: org.opencontainers.image.source="https://github.com/${{ github.repository }}"
